name: 'Publish to Github Package Registry'

on:
  push:
    branches:
      - main

jobs:
  Publish:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm run build
          npm publish